### ISSUE TITLE
cannot be loaded as a native browser esm

### ISSUE THREAD

**Issue by kapouer** [miraclx/xbytes#3]
Hi,

```import xbytes from "/node_modules/xbytes/dist/index.js"```
just won't work because there are no exported symbols.

See for example [how flatpickr declares it in package.json](https://github.com/flatpickr/flatpickr/blob/d5c3029120708636b37d780810899a02af6d03b3/package.json#L53-L54).

**Comment by miraclx** [comment]
Hi @kapouer, if it's no trouble could you set up a PR that addresses this?

I don't use esm myself so if you could help in this regard, it would be greatly appreciated

Thanks in advance
