### ISSUE TITLE
Dist files have different exports

### ISSUE THREAD

**Issue by liamdawson** [miraclx/xbytes#7]
When using `xbytes` with TypeScript in Astro, I ran into an issue in the browser (Astro bundles it using Vite):

```
util.ts:1 Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/xbytes.js?v=066f8229' does not provide an export named 'parseSize' (at util.ts:1:1)
```

The line in question is:

```typescript
import { parseSize } from "xbytes";
```

Code using this import style works in my Jest tests, and it matches the TypeScript types so I was surprised when this failed in the browser. When digging into the `dist` outputs in the `xbytes` package in my `node_modules` directory, I noticed two files, `index.js` and `index.mjs`. They seem to have different export styles:

```javascript
// index.js

function xbytes() {
  // ...
}
// ...
xbytes.parseSize = parseSize;
if (typeof module !== 'undefined') module.exports = xbytes;
```

```javascript
// index.mjs

function xbytes() {
  ...
}
...
xbytes.parseSize = parseSize;
if (typeof module !== 'undefined') module.exports = xbytes;
export default xbytes;
```

My guess is that Jest is loading `xbytes` via the `index.js` file, and that Vite is loading it from the `index.mjs` file, and that the `index.mjs` file only has the single default export.

**Comment by liamdawson** [comment]
Viewing the suggestion at https://github.com/miraclx/xbytes/pull/4#issuecomment-756936220 - I was able to reproduce the issue by adding `"type": "module"` to the project's `package.json` and running this Node file:

```javascript
// test.js
import {parseSize} from 'xbytes';

console.log(parseSize);
```

```shell
$ node test.js
file:///Users/liamdawson/w/github.com/liamdawson/xbytes/test.js:1
import {parseSize} from 'xbytes';
        ^^^^^^^^^
SyntaxError: The requested module 'xbytes' does not provide an export named 'parseSize'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v18.3.0
```

**Comment by miraclx** [comment]
Updated NPM package: https://www.npmjs.com/package/xbytes/v/1.8.0
